name: Daily Notion Automation

on:
  schedule:
    # Trigger every day at midnight UTC (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to manually click "Run workflow" to test it anytime

jobs:
  run-notion-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7

      - name: Set up Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install Notion API dependency
        run: npm install @notionhq/client

      - name: Execute Automation Script
        env:
          # Pulls the hidden token from GitHub settings securely
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          SUBSC_DATA_SOURCE_ID: ${{ secrets.SUBSC_DATA_SOURCE_ID }}
          EXPENSE_DATA_SOURCE_ID: ${{ secrets.EXPENSE_DATA_SOURCE_ID }}
          HH_USD_DATA_SOURCE_ID: ${{ secrets.HH_USD_DATA_SOURCE_ID }}
          HH_JPY_DATA_SOURCE_ID: ${{ secrets.HH_JPY_DATA_SOURCE_ID }}
        run: node notion_automation.js
